In [1]:
import pandas as pd

In [14]:
df = pd.read_csv("train.csv")
snp_info=pd.read_csv("snp_info.csv")
print(df.info())
display(df.head())
display(snp_info.head())

<class 'pandas.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      262 non-null    str
 1   father  262 non-null    int64
 2   mother  262 non-null    int64
 3   gender  262 non-null    int64
 4   trait   262 non-null    int64
 5   SNP_01  262 non-null    str
 6   SNP_02  262 non-null    str
 7   SNP_03  262 non-null    str
 8   SNP_04  262 non-null    str
 9   SNP_05  262 non-null    str
 10  SNP_06  262 non-null    str
 11  SNP_07  262 non-null    str
 12  SNP_08  262 non-null    str
 13  SNP_09  262 non-null    str
 14  SNP_10  262 non-null    str
 15  SNP_11  262 non-null    str
 16  SNP_12  262 non-null    str
 17  SNP_13  262 non-null    str
 18  SNP_14  262 non-null    str
 19  SNP_15  262 non-null    str
 20  class   262 non-null    str
dtypes: int64(4), str(17)
memory usage: 43.1 KB
None

,id,father,mother,gender,trait,SNP_01,SNP_02,SNP_03,SNP_04,SNP_05,...,SNP_07,SNP_08,SNP_09,SNP_10,SNP_11,SNP_12,SNP_13,SNP_14,SNP_15,class
0,TRAIN_000,0,0,0,2,G G,A G,A A,G A,C A,...,A A,G G,A A,G G,A G,A A,A A,A A,A A,B
1,TRAIN_001,0,0,0,2,A G,A G,C A,A A,A A,...,A A,G A,A A,A G,A A,G A,G G,A A,A A,C
2,TRAIN_002,0,0,0,2,G G,G G,A A,G A,C C,...,A A,G A,G A,A G,A A,A A,A A,A A,A A,B
3,TRAIN_003,0,0,0,1,A A,G G,A A,G A,A A,...,G G,A A,G G,A G,G G,G G,G G,A A,G G,A
4,TRAIN_004,0,0,0,2,G G,G G,C C,A A,C C,...,A A,A A,A A,G G,A A,A A,A G,A A,G A,C

   SNP_id                                   name  chrom       cm       pos
0  SNP_01                        BTA-19852-no-rs      2  67.0546  42986890
1  SNP_02  ARS-USMARC-Parent-DQ647190-rs29013632      6  31.1567  13897068
2  SNP_03                    ARS-BFGL-NGS-117009      6  68.2892  44649549
3  SNP_04                     ARS-BFGL-NGS-60567      6  77.8749  53826064
4  SNP_05                     BovineHD0600017032      6  80.5015  61779512

In [2]:
import pandas as pd
test = pd.read_csv("test.csv")
test.head()

,id,father,mother,gender,trait,SNP_01,SNP_02,SNP_03,SNP_04,SNP_05,SNP_06,SNP_07,SNP_08,SNP_09,SNP_10,SNP_11,SNP_12,SNP_13,SNP_14,SNP_15
0,TEST_000,0,0,0,1,A G,G G,A A,G A,A A,A G,G G,G A,G A,A G,A G,G A,G G,C A,G A
1,TEST_001,0,0,0,2,G G,A G,C C,G G,C C,A A,A A,A A,A A,G G,A G,A A,A A,A A,A A
2,TEST_002,0,0,0,2,G G,A G,A A,A A,C A,A G,A A,A A,A A,A G,A A,G A,G G,A A,G G
3,TEST_003,0,0,0,2,G G,A G,C A,A A,C C,A A,A A,A A,A A,G G,A A,G A,A G,A A,A A
4,TEST_004,0,0,0,1,A A,G G,A A,G G,A A,G G,G G,A A,G G,A G,G G,G A,G G,A A,G G

In [4]:
print(df.duplicated().sum())
print(df.isnull().sum())

0
id        0
father    0
mother    0
gender    0
trait     0
SNP_01    0
SNP_02    0
SNP_03    0
SNP_04    0
SNP_05    0
SNP_06    0
SNP_07    0
SNP_08    0
SNP_09    0
SNP_10    0
SNP_11    0
SNP_12    0
SNP_13    0
SNP_14    0
SNP_15    0
class     0
dtype: int64

In [23]:
print("gender 범주:", df['id'].unique())
print("gender 범주별 빈도:")
print(df['id'].value_counts())

gender 범주: <StringArray>
['TRAIN_000', 'TRAIN_001', 'TRAIN_002', 'TRAIN_003', 'TRAIN_004', 'TRAIN_005',
 'TRAIN_006', 'TRAIN_007', 'TRAIN_008', 'TRAIN_009',
 ...
 'TRAIN_252', 'TRAIN_253', 'TRAIN_254', 'TRAIN_255', 'TRAIN_256', 'TRAIN_257',
 'TRAIN_258', 'TRAIN_259', 'TRAIN_260', 'TRAIN_261']
Length: 262, dtype: str
gender 범주별 빈도:
id
TRAIN_000    1
TRAIN_001    1
TRAIN_002    1
TRAIN_003    1
TRAIN_004    1
            ..
TRAIN_257    1
TRAIN_258    1
TRAIN_259    1
TRAIN_260    1
TRAIN_261    1
Name: count, Length: 262, dtype: int64

In [ ]:
print("SNP_01 범주:", df['SNP_01'].unique())
print("\nSNP_01 범주별 빈도:")
print(df['SNP_01'].value_counts())

In [21]:
print(df['class'].value_counts())
print(df['trait'].describe())
print(df['trait'].unique())

class
B    114
C     79
A     69
Name: count, dtype: int64
count    262.000000
mean       1.736641
std        0.441298
min        1.000000
25%        1.000000
50%        2.000000
75%        2.000000
max        2.000000
Name: trait, dtype: float64
[2 1]

In [26]:
#df = df.drop(columns=['father', 'mother', 'gender'])
df.head()

,id,trait,SNP_01,SNP_02,SNP_03,SNP_04,SNP_05,SNP_06,SNP_07,SNP_08,SNP_09,SNP_10,SNP_11,SNP_12,SNP_13,SNP_14,SNP_15,class
0,TRAIN_000,2,G G,A G,A A,G A,C A,A A,A A,G G,A A,G G,A G,A A,A A,A A,A A,B
1,TRAIN_001,2,A G,A G,C A,A A,A A,A G,A A,G A,A A,A G,A A,G A,G G,A A,A A,C
2,TRAIN_002,2,G G,G G,A A,G A,C C,G G,A A,G A,G A,A G,A A,A A,A A,A A,A A,B
3,TRAIN_003,1,A A,G G,A A,G A,A A,G G,G G,A A,G G,A G,G G,G G,G G,A A,G G,A
4,TRAIN_004,2,G G,G G,C C,A A,C C,A A,A A,A A,A A,G G,A A,A A,A G,A A,G A,C

In [29]:
snp_cols = [f'SNP_{i:02d}' for i in range(1, 16)]

for col in snp_cols:
    print(f"\n===== {col} =====")
    print(df[col].value_counts())

===== SNP_01 =====
SNP_01
G G    141
A G     71
A A     50
Name: count, dtype: int64

===== SNP_02 =====
SNP_02
G G    108
A G     97
A A     57
Name: count, dtype: int64

===== SNP_03 =====
SNP_03
A A    122
C A     92
C C     48
Name: count, dtype: int64

===== SNP_04 =====
SNP_04
A A    120
G A     93
G G     49
Name: count, dtype: int64

===== SNP_05 =====
SNP_05
A A    94
C A    86
C C    82
Name: count, dtype: int64

===== SNP_06 =====
SNP_06
A G    122
G G     79
A A     61
Name: count, dtype: int64

===== SNP_07 =====
SNP_07
A A    163
G G     51
G A     48
Name: count, dtype: int64

===== SNP_08 =====
SNP_08
G A    96
A A    87
G G    79
Name: count, dtype: int64

===== SNP_09 =====
SNP_09
A A    182
G A     56
G G     24
Name: count, dtype: int64

===== SNP_10 =====
SNP_10
G G    151
A G     68
A A     43
Name: count, dtype: int64

===== SNP_11 =====
SNP_11
A G    96
A A    83
G G    83
Name: count, dtype: int64

===== SNP_12 =====
SNP_12
A A    136
G A     73
G G     53
Name: count, dtype: int64

===== SNP_13 =====
SNP_13
G G    115
A G     95
A A     52
Name: count, dtype: int64

===== SNP_14 =====
SNP_14
A A    185
C A     54
C C     23
Name: count, dtype: int64

===== SNP_15 =====
SNP_15
A A    107
G A    100
G G     55
Name: count, dtype: int64

In [30]:
snp_cols = [f'SNP_{i:02d}' for i in range(1, 16)]

for col in snp_cols:
    print(f"\n===== {col} =====")
    print(df[col].value_counts())

===== SNP_01 =====
SNP_01
G G    141
A G     71
A A     50
Name: count, dtype: int64

===== SNP_02 =====
SNP_02
G G    108
A G     97
A A     57
Name: count, dtype: int64

===== SNP_03 =====
SNP_03
A A    122
C A     92
C C     48
Name: count, dtype: int64

===== SNP_04 =====
SNP_04
A A    120
G A     93
G G     49
Name: count, dtype: int64

===== SNP_05 =====
SNP_05
A A    94
C A    86
C C    82
Name: count, dtype: int64

===== SNP_06 =====
SNP_06
A G    122
G G     79
A A     61
Name: count, dtype: int64

===== SNP_07 =====
SNP_07
A A    163
G G     51
G A     48
Name: count, dtype: int64

===== SNP_08 =====
SNP_08
G A    96
A A    87
G G    79
Name: count, dtype: int64

===== SNP_09 =====
SNP_09
A A    182
G A     56
G G     24
Name: count, dtype: int64

===== SNP_10 =====
SNP_10
G G    151
A G     68
A A     43
Name: count, dtype: int64

===== SNP_11 =====
SNP_11
A G    96
A A    83
G G    83
Name: count, dtype: int64

===== SNP_12 =====
SNP_12
A A    136
G A     73
G G     53
Name: count, dtype: int64

===== SNP_13 =====
SNP_13
G G    115
A G     95
A A     52
Name: count, dtype: int64

===== SNP_14 =====
SNP_14
A A    185
C A     54
C C     23
Name: count, dtype: int64

===== SNP_15 =====
SNP_15
A A    107
G A    100
G G     55
Name: count, dtype: int64

In [31]:
print(df['trait'].dtype)

int64

In [33]:
print(df['trait'].unique())
print(df['trait'].value_counts())

[2 1]
trait
2    193
1     69
Name: count, dtype: int64

In [37]:
df['trait'] = df['trait'].astype('object')

In [38]:
print(df['trait'].dtype)

object

In [41]:
display(pd.crosstab(df['trait'], df['class']))
display(df.groupby('trait')['class'].value_counts(normalize=True))

class   A    B   C
trait
1      69    0   0
2       0  114  79

trait  class
1      A        1.000000
2      B        0.590674
       C        0.409326
Name: proportion, dtype: float64

In [43]:
for col in [f'SNP_{i:02d}' for i in range(1, 16)]:
    print(f'\n[{col}]')
    print(pd.crosstab(df[col], df['trait'], normalize='index'))

[SNP_01]
trait          1         2
SNP_01
A A     0.900000  0.100000
A G     0.295775  0.704225
G G     0.021277  0.978723

[SNP_02]
trait          1         2
SNP_02
A A     0.000000  1.000000
A G     0.061856  0.938144
G G     0.583333  0.416667

[SNP_03]
trait          1         2
SNP_03
A A     0.565574  0.434426
C A     0.000000  1.000000
C C     0.000000  1.000000

[SNP_04]
trait          1         2
SNP_04
A A     0.016667  0.983333
G A     0.333333  0.666667
G G     0.734694  0.265306

[SNP_05]
trait          1         2
SNP_05
A A     0.585106  0.414894
C A     0.162791  0.837209
C C     0.000000  1.000000

[SNP_06]
trait          1         2
SNP_06
A A     0.000000  1.000000
A G     0.163934  0.836066
G G     0.620253  0.379747

[SNP_07]
trait       1      2
SNP_07
A A     0.000  1.000
G A     0.375  0.625
G G     1.000  0.000

[SNP_08]
trait          1         2
SNP_08
A A     0.666667  0.333333
G A     0.114583  0.885417
G G     0.000000  1.000000

[SNP_09]
trait          1         2
SNP_09
A A     0.071429  0.928571
G A     0.589286  0.410714
G G     0.958333  0.041667

[SNP_10]
trait          1         2
SNP_10
A A     0.744186  0.255814
A G     0.500000  0.500000
G G     0.019868  0.980132

[SNP_11]
trait          1         2
SNP_11
A A     0.000000  1.000000
A G     0.135417  0.864583
G G     0.674699  0.325301

[SNP_12]
trait          1         2
SNP_12
A A     0.007353  0.992647
G A     0.273973  0.726027
G G     0.905660  0.094340

[SNP_13]
trait          1         2
SNP_13
A A     0.000000  1.000000
A G     0.031579  0.968421
G G     0.573913  0.426087

[SNP_14]
trait          1         2
SNP_14
A A     0.059459  0.940541
C A     0.685185  0.314815
C C     0.913043  0.086957

[SNP_15]
trait          1         2
SNP_15
A A     0.037383  0.962617
G A     0.210000  0.790000
G G     0.800000  0.200000

In [45]:
# 전체 데이터에서 trait와 class의 관계
pd.crosstab(
    df['trait'],
    df['class'],
    margins=True
)

class   A    B   C  All
trait
1      69    0   0   69
2       0  114  79  193
All    69  114  79  262

In [46]:
pd.crosstab(
    df['trait'],
    df['class'],
    normalize='index'
).round(3)

class    A      B      C
trait
1      1.0  0.000  0.000
2      0.0  0.591  0.409

In [47]:
# class별 trait 분포
pd.crosstab(
    df['class'],
    df['trait'],
    normalize='index'
).round(3)

trait    1    2
class
A      1.0  0.0
B      0.0  1.0
C      0.0  1.0